spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/EnterpriseSystem
spring.datasource.username=postgres
spring.datasource.password=bibek
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
jwt.secretKey=absjhvbfjh345jhvejshfv89237y4hsgvdfhcsj2893y4rshgdvch32847yrshv

